# Header
menu:
  首页: /
  归档: /archives
  关于: /about/index.html
rss: 
github: https://github.com/ppoffice/hexo-theme-alex

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: left
widgets:
- category
- archive
- recent_posts
- tag
- tagcloud
- links

# Links
links: 
  Hexo: http://hexo.io

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: 
duoshuo_shortname: 猿笔记